server:
  port: 9000 # 端口

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  application:
    name: flight-gateway-server # 应用名称
  cloud:
    gateway:
      # 路由规则
      routes:
        - id: flight-provider-user           # 路由 ID，唯一
          uri: lb:flight-provider-user   # 目标 URI，路由到微服务的地址
          predicates:                   # 断言（判断条件）
            - Path=/product/**          # 匹配对应 URL 的请求，将匹配到的请求追加在目标 URI 之后